# Generated by Django 4.0.4 on 2022-04-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='year',
            field=models.CharField(max_length=4, verbose_name='create_year'),
        ),
    ]
