version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9432:5432"
